name: PDF Release

on:
  release:
    types: [published]

jobs:
  container-build-pdf:
    runs-on: ubuntu-latest
    container:
      image: arkark/latexmk:full
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          apt-get update
          apt-get install -y --no-install-recommends python3 python3-pip python3-pexpect pylint libimage-exiftool-perl

      - name: Install pygments
        run: pip3 install Pygments
        
      - name: Build PDF
        run: latexmk && latexmk && latexmk
      
      - name: Tag PDF
        run: exiftool -Producer="Repository=${{ github.server_url }}/${{ github.repository }}, Run_ID=${{github.run_id}}, Commit=${{ github.sha }}, XeLaTeX and some love <3" main.pdf
        
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with: 
          name: main.pdf
          if-no-files-found: error
          path: main.pdf
    
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: main.pdf